import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const p = await b.newPage({ viewport:{width:1280,height:1000} });
const errs=[]; p.on('pageerror',e=>errs.push(e.message.split(String.fromCharCode(10))[0]));
await p.goto('file:///private/tmp/claude-501/-Users-griffinsurett-coding-2025-Website-Projects-2026/0ed8baee-e954-444a-9d49-1c49d333484e/scratchpad/wcag-audit-copy.html', {waitUntil:'load'});
await p.evaluate(()=>['gws-wcag-fixed-v2','gws-wcag-reach-v1','gws-wcag-hidedone-v1'].forEach(k=>localStorage.removeItem(k)));
await p.reload({waitUntil:'load'}); await p.waitForTimeout(400);
const c=()=>p.evaluate(()=>document.querySelectorAll('article.find.rf-hide').length);
console.log('hidden initial:', await c());
await p.click('.rf-btn[data-reach="reuse"]'); await p.waitForTimeout(300);
console.log('after Reusable click, hidden:', await c());
await p.click('#rf-hide-done'); await p.waitForTimeout(300);
console.log('after Hide-fixed click, hidden:', await c(), '| N left:', await p.evaluate(()=>document.getElementById('rf-c-open').textContent));
console.log('errors:', errs.slice(0,3));
await b.close();
